#!/bin/bash
set -e

_pid() {
    pgrep -fx "node.*--port $WETTY_PORT .*" || true
}

start() {
    local title="$*"
    local pid="$(_pid)"
    [[ -z $pid ]] || {
        echo "already started" 1>&2
        exit 1
    }
    source $NVM_DIR/nvm.sh
    cd $WETTY_DIR
    echo "logging to /var/tmp/wetty.out"
    #WETTY_PORT=3000 # XXXXXXXXXXXXXXXXXXX
    nvm exec $WETTY_NODE_VERSION node . \
        --base / --host 0.0.0.0 --port $WETTY_PORT --title "$title" \
        >&1 > /var/tmp/wetty.out &
}

stop() {
    local pid="$(_pid)"
    [[ -z $pid ]] && {
        echo "already stopped" 1>&2
        exit 1
    }
    kill $pid
}

status() {
    if [[ -z "$(_pid)" ]]; then
        echo stopped
        exit 1
    else
        echo running
        exit 0
    fi
}

########################

source $(dirname $0)/../config.sh

case "$1" in
start|stop|status)
    eval "$@"
    ;;
*)
    echo "Usage: $0 (start|stop|status)" 1>&2
    exit 2
    ;;
esac
