#!/bin/bash
set -e

_pid() {
    pgrep -fx "node.*--port $THEIA_PORT .*" || true
}

start() {
    local pid="$(_pid)"
    [[ -z $pid ]] || {
        echo "already started" 1>&2
        exit 1
    }
    source $NVM_DIR/nvm.sh
    cd $THEIA_DIR/examples/browser
    nvm exec $THEIA_NODE_VERSION yarn run start --port $THEIA_PORT "\$@" &
}

stop() {
    local pid="$(_pid)"
    [[ -z $pid ]] && {
        echo "already stopped" 1>&2
        exit 1
    }
    kill $pid
}

status() {
    if [[ -z "$(_pid)" ]]; then
        echo stopped
        exit 1
    else
        echo running
        exit 0
    fi
}

########################

source $(dirname $0)/../config.sh

case "$1" in
start|stop|status)
    eval "$@"
    ;;
*)
    echo "Usage: $0 (start|stop|status)" 1>&2
    exit 2
    ;;
esac
