#!/bin/bash
set -e

pid=/tmp/theia.pid

start() {
    local title="$1"
    [[ $# = 1 ]] || usage "TITLE"
    source $(dirname $0)/../config.sh
    source $NVM_DIR/nvm.sh
    cd $THEIA_DIR/examples/browser
    nvm exec $node_version yarn run start --port 3001 "\$@" &
    echo $$ > $pid
}

stop() {
    [[ -r $pid ]] || {
        echo "$0: $pid not found" 1>&2
        exit 1
    }
    kill $(< $pid)
    rm $pid
}

status() {
    if [[ -f $pid && pgrep -F $pid &> /dev/null ]]; then
        echo running
        exit 0
    else
        echo stopped
        exit 1
    fi
}

case "$1" in
start|stop|status)
    eval "$@"
    ;;
*)
    echo "Usage: $0 (start|stop|status)" 1>&2
    exit 2
    ;;
esac
