#!/bin/bash
# tmux utilities
#exit 0

set -e

status() {
    while :; do
        local repos=$(pod repos)
        [[ -z "$repos" ]] || echo -n "| $repos "
        local secrets=$(pod secrets status)
        [[ -z "$secrets" ]] || echo -n "| $secrets "
        echo "| pairing: $(pod pairing status)"
        sleep 15
    done
}

banner() {
    tmux new-window -n MESSAGE "clear && figlet -f big '$*' && read"
}

message() {
    tmux display-message "$*"
}

# Open dir in new window, with vertical split
v2() {
    local dir="$1"
    [[ -d "$dir" ]] || {
        echo "Usage: $0 v2 DIR" 1>&2
        exit 2
    }
    local name="$(basename $dir)"
    tmux new-window -n "$name" -c "$dir"
    tmux split-window -h -c "$dir"
    tmux select-pane -t 0
    tmux send-keys vim 'Space' . 'Enter'
    tmux select-pane -t 1
}

init() {
    ls ~/src/* &> /dev/null || return 0
    for repo in ~/src/*; do
        v2 $repo
    done
}

case $1 in
init|status|message|banner|v2)
    eval "$@"
    ;;
*)
    echo "Usage: $0 (status|message|banner|v2)" 1>&2
    exit 2
    ;;
esac
