#!/bin/bash
# Encrypts ~/.pod/secrets into ~/.pod-secrets.gpg and back

set -e

SECRETS=$HOME/.pod/secrets
ARCHIVE=$HOME/.pod-secrets.gpg
export GPG_TTY=$(tty)
cd

([[ -f .gitignore ]] && grep -q "^/.pod/$" ~/.gitignore) || {
    echo "$0: /.pod/ not in .gitignore" 1>&2
    exit 1
}

kill_gpg_agent() {
    pkill gpg-agent 2> /dev/null || true
}

case $1 in
encrypt) 
    [[ -d $SECRETS ]] || {
        echo "$0: Missing secrets directory $SECRETS" 1>&2
        exit 1
    }
    rm -f $ARCHIVE
    cd $(dirname $SECRETS)   
    kill_gpg_agent
    tar cfz - $(basename $SECRETS) | gpg -c --cipher-algo aes256 -o $ARCHIVE
    kill_gpg_agent
    ;;
decrypt) 
    rm -rf $SECRETS
    mkdir -p ~/.pod
    kill_gpg_agent
    gpg -d --cipher-algo aes256 $ARCHIVE | tar xfz -
    kill_gpg_agent
    chmod -R go-rwx $SECRETS
    ;;
status)
    [[ -d $SECRETS ]] && {
        latest=$(find $SECRETS -type f | xargs ls -t | head -1)
        [[ ! -z "$latest" &&  $latest -nt $ARCHIVE ]] && {
            echo "uncommitted secrets"
            exit 1
        }
    }
    exit 0
    ;;
*)
    echo "Usage: pod secrets (encrypt|decrypt|status)" 1>&2
    exit 2
    ;;
esac
