#!/bin/bash
# Example:
# $ ./start-pod columnated/pod:latest 0 wetty 43880338 "Henri" https://github.com/perpen/pod-linux-home.git https://github.com/krishnasrinivas/wetty.git

set -e

source $(dirname $0)/../pod/config.sh

POD_PORT_RANGE_START=3000
POD_PORT_RANGE_WIDTH=10

[[ $# -lt 3 ]] && {
    echo "Usage: $(basename $0) IMAGE POD_NUMBER ENTRYPOINT_PARAM ..." 1>&2
    exit 2
}

image="$1"
pod_number="$2"
shift 2

pod_name="p$pod_number"
ssh_port=$(( $POD_PORT_RANGE_START + $pod_number * $POD_PORT_RANGE_WIDTH - 0))
pod_port=$(( $ssh_port + 1 ))
pod_dir=$(readlink -f $(dirname $0)/../pod)

set -x
# pod/runtime/entrypoint args: OPTIONS USER USER_DISPLAY_NAME GIT_URL_HOMEDIR [GIT_URL ...]
docker run --rm \
    --name "$pod_name" \
    --hostname "$pod_name" \
    -v $pod_dir:/pod \
    -p $ssh_port:22 \
    -p $pod_port:3000 \
    $image \
    $pod_number "$@"
