#!/bin/bash
# Dockerfile entry point, runs the non-interactive user-dependent stuff

set -ex

[[ $# -lt 3 ]] && {
    cat <<EOF 1>&2
Usage: $0 POD_NUMBER OPTIONS USER USER_DISPLAY_NAME GIT_URL_HOMEDIR [GIT_URL ...]
    OPTIONS For now use 'none'
EOF
    exit 2
}

export POD_NUMBER="$1"
export POD_OPTIONS="$2"
export POD_USER="$3"
export POD_USER_DISPLAY_NAME="$4"
export POD_HOMEDIR_URL="$5"
shift 5
export POD_PROJECTS_URLS="$*"

source $(dirname $0)/../config.sh

create_user() {
    # Centos doesn't allow usernames like \d+, so we create a temp user which we
    # then rename.
    [[ -d /home/$POD_USER ]] || {
        local tmp_user=x$POD_USER
        adduser -s /bin/bash -g pair $tmp_user
        echo "$tmp_user:pass" | chpasswd
        for file in /etc/{passwd,shadow,shadow-,group,gshadow}; do
            sed -i "s/$tmp_user/$POD_USER/g" $file
        done
        mv /home/{$tmp_user,$POD_USER}
        sed -i "s/^\(wheel:.*\)$/\1,$POD_USER/" /etc/group
        sed -i "s/^\(pair:.*\)$/\1,$POD_USER/" /etc/group
        echo $POD_USER >> /etc/at.allow
    }
}

store_pod_params() {
    # Save params to environment and ~/.pod/params.json
    # FIXME do i still need the json?
    local params_dir=/home/$POD_USER/.pod
    mkdir $params_dir
    cat <<EOF > "$params_dir/params.json"
{
  "pod_number": $POD_NUMBER,
  "options": "$POD_OPTIONS",
  "user": "$POD_USER",
  "user_display_name": "$POD_USER_DISPLAY_NAME",
  "homedir_url": "$POD_HOMEDIR_URL",
  "projects_urls": "$POD_PROJECTS_URLS"
}
EOF
    chown -R $POD_USER:pair $params_dir
}

watch_deadly_file() {
    set +x
    while :; do
        [[ -f /tmp/pod-must-die ]] && {
            kill 1 || true
        }
        sleep 10
    done &
    set -x
}

start_apps() {
    # Start UIs
    pod wetty start "pod $POD_NUMBER"
    pod theia start

    # Start pod app
    set +x
    source $NVM_DIR/nvm.sh
    nvm use $POD_NODE_VERSION
    set -x
    su $POD_USER -c "node /pod/runtime/app/pod.js" &
}

##########################

create_user
store_pod_params
su $POD_USER -c "/pod/runtime/user-init $POD_HOMEDIR_URL $POD_PROJECTS_URLS"
watch_deadly_file
start_apps

ssh-keygen -A
/usr/sbin/sshd -D
